### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by exactt** [Schluggi/pymap-copy#12]
Hi,

the server at mx.ccn.net gives the following error:

Getting source folders      : Traceback (most recent call last):
  File "/home/max/pymap-copy/pymap-copy/utils.py", line 57, in decode_mime
    words.append(word.decode(encoding or 'utf8'))
LookupError: unknown encoding: dos-862

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pymap-copy.py", line 220, in <module>
    subject = decode_mime(data[b'ENVELOPE'].subject)
  File "/home/max/pymap-copy/pymap-copy/utils.py", line 62, in decode_mime
    words.append(fallback(word))
  File "/home/max/pymap-copy/pymap-copy/utils.py", line 43, in fallback
    return mime_bytes.decode(charset)
TypeError: decode() argument 'encoding' must be str, not None

**Comment by Schluggi** [comment]
@exactt I'm really happy about the first "real" issue. Sadly i can't fix it at this moment because I'm in holiday.

Same

**Comment by Schluggi** [comment]
I've made some changes in the decode_mime() function.
This should fix your issues. 

Feedback is welcome :)
